---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-dev
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: juane
  annotations:
    google.com/email: juanescalada175@gmail.com
spec:
  profile:
    displayName: Juan E.
    email: juanescalada175@gmail.com
    picture: https://example.com/your-profile-picture.png
  memberOf: # Optional; groups the user belongs to
    - team-example
